### ISSUE TITLE
03 images

### ISSUE THREAD

**Issue by kennyd98** [studye/rxjs#3]

**Comment by kennyd98** [comment]
![default](https://cloud.githubusercontent.com/assets/877691/18224001/db596e14-7202-11e6-9663-242f83cad600.PNG)

![2](https://cloud.githubusercontent.com/assets/877691/18224003/e6820b20-7202-11e6-8ce7-77bfdc71e4ea.PNG)

**Comment by casiru** [comment]
![cycle1](https://cloud.githubusercontent.com/assets/4188058/19225308/e5d5d01e-8ed4-11e6-83e4-d0b8ea4209d1.PNG)

**Comment by casiru** [comment]
![cycle2](https://cloud.githubusercontent.com/assets/4188058/19225310/f337918e-8ed4-11e6-8b5d-3c54db9b85ed.PNG)

**Comment by sculove** [comment]
![2016-10-28 12 39 31](https://cloud.githubusercontent.com/assets/1383952/19774167/16c221fc-9ca7-11e6-97b6-ceb56607ba1e.png)

**Comment by sculove** [comment]
![2016-10-28 12 51 11](https://cloud.githubusercontent.com/assets/1383952/19774623/b824a7e4-9ca8-11e6-990f-5b1e81526c3c.png)

**Comment by sculove** [comment]
![2016-10-31 10 58 27](https://cloud.githubusercontent.com/assets/1383952/19842162/625706a0-9f59-11e6-99f6-a61c34574316.png)
